### ISSUE TITLE
Allow nested manipulates

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/Interact.jl#164] opened 2017-05-07 20:53 UTC
I want to be able to nest manipulates where inner ones are affected by outer ones.

This currently causes the jupyter notebook to stall out

----------------

Simple example:

```
some_dict = Dict(
  "arc" => 3.3, 
  "act1" => 6.8, 
  "act2" => 9.6
)

@manipulate for design=["arc", "act1", "act2"]
    @manipulate for r=linspace(0, some_dict[design], 25)
         cur_design = load_design(design)
         foo(cur_design, r)
    end
end;
```

**Comment by JobJob** [comment] 2017-05-08 07:41
Yep, `@manipulate` has limitations. If you want to build more complicated UIs you're better off handling the widgets and signals manually. E.g. for the above:
```
some_dict = Dict(
  "arc" => 3.3, 
  "act1" => 6.8, 
  "act2" => 9.6
)

design_chooser = togglebuttons(["arc", "act1", "act2"]; label="design")
range_sig = map(design_val->linspace(0, some_dict[design_val], 25), signal(design_chooser))
r_slider = slider(value(range_sig); label="r")
set!(r_slider, :range, range_sig) # update the slider's range when the range_sig updates
design_updater = map(signal(design_chooser), signal(r_slider)) do design, r
    cur_design = load_design(design)
    foo(cur_design, r)
end
display.([design_chooser, r_slider, design_updater]);
```

**Comment by JobJob** [comment] 2017-05-15 11:46
The stalling was caused by a couple of bugs arising from recent changes in Reactive to get it work on 0.6. The PRs to fix those, and another issue your code brought up for me, (https://github.com/JuliaGizmos/Reactive.jl/pull/138 and https://github.com/JuliaGizmos/Reactive.jl/pull/139) should be merged soon. In the meantime I'd recommend trying `Pkg.checkout("Reactive", "job/flatten-bind-fix")` it should be much more reliable. Unfortunately it won't fix the OP, but you'll see that it _almost_ works, just a new slider for `r` gets created every time you choose a new design. 

This is strongly related to #12 and it would be nice to fix this. I'm hopeful I'll get a chance to as part of my GSoC work on Interact

Anyway, thanks for the report, it helped me track down a couple of subtle bugs in Reactive.

**Comment by JobJob** [comment] 2017-05-16 06:44
Those PRs are merged. Party time all round :tada:

**Comment by djsegal** [comment] 2017-06-12 22:03
@JobJob just confirming this is ok to close?

**Comment by djsegal** [comment] 2017-08-08 17:05
If you click an outer scope option, the inner scope options get re-appended

i.e.

<img width="1023" alt="screen shot 2017-08-08 at 1 04 45 pm" src="https://user-images.githubusercontent.com/3156114/29084515-391e39b6-7c3a-11e7-93fc-60da4d506160.png">

**Comment by djsegal** [comment] 2017-08-12 18:40
@JobJob, are you able to reproduce this?

**Comment by JobJob** [comment] 2017-08-13 03:27
Yep. Leave this issue open so it stays on the radar

**Comment by djsegal** [comment] 2017-08-25 04:30
I'm interested in helping fix this issue. Do you know where abouts to look?

**Comment by JobJob** [comment] 2017-08-25 07:49
Yeah, it's gonna be pretty fiddly, and IJulia specific. Probably better to try implement it in InteractNext once it's released, which should be next week, though expect it to be a bit brittle at first.

A basic approach that might work is to get the widgets to become `Signal{Widget}`s, and then Interact can handle them updating.

As I wrote [above](https://github.com/JuliaGizmos/Interact.jl/issues/164#issuecomment-299795644), if you want to build more complicated UIs, you're probably better off handling the widgets and signals manually for now, rather than using manipulate.

**Comment by jasongrout** [comment] 2017-09-14 13:00
FYI, supporting interacts inside interacts works well (at least in python) in ipywidgets 7.

**Comment by piever** [comment] 2018-07-11 16:36
I just tried:

```julia
using InteractBulma
some_dict = Dict(
  "arc" => 3.3, 
  "act1" => 6.8, 
  "act2" => 9.6
)

@manipulate for design=["arc", "act1", "act2"]
    @manipulate for r=linspace(0, some_dict[design], 25)
         r
    end
end
```

and it seems to just work. Let me know if there are more things to be done on this front or whether the issue can simply be closed.

**Comment by djsegal** [comment] 2018-07-11 18:56
You can close it

**Closed** 2018-07-11 19:14 UTC
