### ISSUE TITLE
no output on jupyter

### ISSUE THREAD

**Issue by poldavezac** [JuliaGizmos/Interact.jl#294] opened 2019-02-20 20:21 UTC
The following displays nothing in Jupyter, with or without the last line:

"""
Using Interact
s = slider(1:10)
display(s)
"""

I get an javascript error  message upon the first line:

""""
SyntaxError: expected expression, got '<'
m http://localhost:8888/static/notebook/js/main.min.js?v=afeb95b32523abb04bdecc3bfd996f00:2 globalEval http://localhost:8888/static/notebook/js/main.min.js?v=afeb95b32523abb04bdecc3bfd996f00:2
...
"""

Current version are: 

  [bf4720bc] AssetRegistry v0.1.0
  [70588ee8] CSSUtil v0.1.0
  [3da002f7] ColorTypes v0.7.5
  [5ae59095] Colors v0.9.5
  [34da2185] Compat v1.5.1
  [864edb3b] DataStructures v0.15.0
  [53c48c17] FixedPointNumbers v0.5.3
  [de31a74c] FunctionalCollections v0.5.0
  [c601a237] Interact v0.9.1
  [d3863d7c] InteractBase v0.8.3
  [7981ab7d] InteractBulma v0.5.0
  [7073ff75] IJulia v1.17.0
  [97c1335a] JSExpr v0.5.0
  [682c06a0] JSON v0.20.0
  [bcebb21b] Knockout v0.2.0
  [1914dd2f] MacroTools v0.4.5
  [442fdcdd] Measures v0.3.0
  [510215fc] Observables v0.2.3
  [bac558e1] OrderedCollections v1.0.2
  [fa939f87] Pidfile v1.1.0
  [189a3867] Reexport v0.2.0
  [ae029012] Requires v0.5.2
  [0f1e0344] WebIO v0.7.0
  [cc8bc4a8] Widgets v0.5.0

with jupyter:
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py37_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.2.0                 py37_1000    conda-forge
jupyter_latex_envs        1.4.4                 py37_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
ipywidgets                7.4.1                      py_0    conda-forge

**Comment by poldavezac** [comment] 2019-02-20 21:14
I also see the following from the server:
[W 22:10:54.185 NotebookApp] 404 GET /assetserver/ab93c3588e0dd4c840e00a104202837c2c162d3f-assets/webio/dist/bundle.js (127.0.0.1) 18.53ms referer=http://localhost:8888/notebooks/Untitled2.ipynb?kernel_name=julia-1.0
[W 22:10:54.211 NotebookApp] 404 GET /assetserver/ab93c3588e0dd4c840e00a104202837c2c162d3f-assets/providers/ijulia_setup.js (127.0.0.1) 3.33ms referer=http://localhost:8888/notebooks/Untitled2.ipynb?kernel_name=julia-1.0

I've checked that both files are available in ~/.julia/packages/WebIO/Rk8wc/assets/

**Comment by SimonEnsemble** [comment] 2019-02-27 05:33
The following example does not display anything for me either in Julia 1.1. Neither in Jupyter Notebook nor Jupyter Lab. All is `] up`.

```
f = figure()
x = range(0, stop=2π, length=1000)
@manipulate for α=1:0.1:3, β=1:0.1:3, γ=1:0.1:3, leg="a funny plot"; withfig(f) do
        PyPlot.plot(x, cos.(α.*x .+ sin.(β.*x .+ γ)))
        legend([leg])
    end
end
```

**Comment by EdoAlvarezR** [comment] 2019-03-05 22:25
Not even the most basic `@manipulate` displays anything to me:

```julia
@manipulate for npp=1:180
    display(npp)
end
```

**Comment by EdoAlvarezR** [comment] 2019-03-05 22:36
Specifying the latest WebIO and and InteracBase did it for me:

```julia
(v1.1) pkg> add WebIO@0.6.2
(v1.1) pkg> add InteractBase@0.8.3
(v1.1) pkg> build Interact
----- Restart Jupyter ----------------
```

**Comment by lazarusA** [comment] 2019-03-06 21:45
@EdoAlvarezR's solution works! 👍

**Comment by EdoAlvarezR** [comment] 2019-03-06 23:10
Yea, I realized this morning that things weren't working again.

After doing
```
(v1.1) pkg> rm Interact
pip2 install jupyter_contrib_nbextensions --user --force
(v1.1) pkg> add Interact
```

now things display on Jupyter, but clicking on any slider or button the Jupyter terminal says 
```
[W 16:07:07.593 NotebookApp] zmq message arrived on closed channel
```
and the `@manipulate` object (a plotly 3D plot in this case) doesn't update.

**Comment by lazarusA** [comment] 2019-03-07 05:46
@EdoAlvarezR you need to remove also 
`] rm WebIO `
`] rm InteractBase`

before reinstalling `Interact`

**Comment by mbaz** [comment] 2019-04-01 13:57
I have the same issue... I removed Interact, InteractBase and WebIO packages, then ran

    [~/.julia/conda/3/bin $] ./conda install -c conda-forge jupyter_contrib_nbextensions

and added `Interact` back, then built it. I still get no output from any of the examples posted here or the two `@manipulate` examples in the tutorial.

**Comment by daemacles** [comment] 2019-04-26 20:07
Also broken for me on Julia 1.1 -- plots etc don't update with `@manipulate`.  Adding jupyter_contrib_nbextensions didn't seem to help at all.

```
Pkg.installed()
  "InteractBase" => v"0.10.1"
  "Conda"        => v"1.2.0"
  "Interact"     => v"0.10.2"
  "IJulia"       => v"1.18.1"
  "Plots"        => v"0.24.0"
  "PyPlot"       => v"2.8.1"
  "Colors"       => v"0.9.5"
  "Gadfly"       => v"1.0.1"
  "WebIO"        => v"0.8.1"
```

**Comment by travigd** [comment] 2019-05-18 03:00
The issue with the OP is definitely the `404 GET /assetserver/` messages. Because WebIO allows the inclusion of arbitrary JS/HTML/CSS content, it sets up its own server within the Jupyter notebook server (so the `/assetserver` requests **should** be served from the files stored within the AssetRegistry).

My guess is that the config file for the notebook isn't correct. What operating system are you using and

**Comment by EdoAlvarezR** [comment] 2019-05-18 04:37
Giving it a shot just now, I removed Interact and installed it again doing the sequence

```julia
(v1.1) pkg> rm Interact
pip2 install jupyter_contrib_nbextensions --user --force
(v1.1) pkg> add Interact
```

Then I started Jupyter, and interact started working just fine. I started writing a notebook, and 5 minutes latter Interact stopped updating in the notebook. It is quite random since I didn't installed or updated any package during that time lapse, I was just writing code in the notebook and using the interact interface to plot some data. No error showed in the terminal.

Here is my test case:

```julia
using Interact

@manipulate for npp=1:180
    display(npp)
end
```
It shows the slider, but it doesn't update the display when manipulated.


This is my Julia 1.1.0 environment:

```julia
(v1.1) pkg> status
    Status `~/.julia/environments/v1.1/Project.toml`
  [6e4b80f9] BenchmarkTools v0.4.2
  [336ed68f] CSV v0.4.3
  [a93c6f00] DataFrames v0.17.1
  [7073ff75] IJulia v1.17.0
  [c601a237] Interact v0.10.2
  [4138dd39] JLD v0.9.1
  [a93385a2] JuliaDB v0.11.2
  [b964fa9f] LaTeXStrings v1.0.3
  [91a5bcdd] Plots v0.23.1
  [d330b81b] PyPlot v2.7.0
  [cd998857] Yota v0.1.3
```

Regarding operative system, here is the Ubuntu release:
```bash
edoalvar@edoalvar:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
```

Here is the `~/.jupyter` folder:
```bash
edoalvar@edoalvar:~$ ls ~/.jupyter/
jupyter_nbconvert_config.json  jupyter_notebook_config.jsonNOT  migrated
jupyter_notebook_config.json   jupyter_notebook_config.py       nbconfig
```
and the `~/.jupyter/nbconfig/` folder:
```bash
edoalvar@edoalvar:~$ ls ~/.jupyter/nbconfig/
notebook_backup.json  notebook.json  tree.json
```

Here is the content of `~/.jupyter/jupyter_notebook_config.py`:
```python
###JULIA-WEBIO-CONFIG-BEGIN
import sys, os
if os.path.isfile("/home/edoalvar/.julia/packages/WebIO/7G1ZY/deps/jlstaticserve.py"):
    sys.path.append("/home/edoalvar/.julia/packages/WebIO/7G1ZY/deps")
    c = get_config()
    c.NotebookApp.nbserver_extensions = {
        "jlstaticserve": True
    }
else:
    print("WebIO config in ~/.jupyter/jupyter_notebook_config.py but WebIO plugin not found")
###JULIA-WEBIO-CONFIG-END
```
If at all important, there are four versions of WebIO in `/home/edoalvar/.julia/packages/WebIO/`:
```bash
edoalvar@edoalvar:~$ ls /home/edoalvar/.julia/packages/WebIO/
7G1ZY  NYISm  Pf4Gm  Rk8wc
```

and here is the content of `~/.jupyter/jupyter_notebook_config.json`:
```json
{
    "NotebookApp": {
        "nbserver_extensions": {
            "jupyter_nbextensions_configurator": true,
            "jlstaticserve": true
        }
    }
}
```

Here is the Jupyter log that prints in the terminal from the moment I launch Jupyter up to the point of running the cell with the slider:
```bash
[W 22:32:28.128 NotebookApp] Collisions detected in /home/edoalvar/.jupyter/jupyter_notebook_config.py and /home/edoalvar/.jupyter/jupyter_notebook_config.json config files. /home/edoalvar/.jupyter/jupyter_notebook_config.json has higher priority: {
      "NotebookApp": {
        "nbserver_extensions": "{'jlstaticserve': True} ignored, using {u'jlstaticserve': True, u'jupyter_nbextensions_configurator': True}"
      }
    }
[I 22:32:28.275 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 22:32:28.276 NotebookApp] Serving notebooks from local directory: /home/edoalvar/Dropbox/FLOWResearch/LabNotebook
[I 22:32:28.277 NotebookApp] The Jupyter Notebook is running at:
[I 22:32:28.277 NotebookApp] http://localhost:8888/?token=cae41efe66230be89ed6efa18e188a501c25c57bc7b80799
[I 22:32:28.277 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:32:28.279 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///run/user/1000/jupyter/nbserver-7717-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=cae41efe66230be89ed6efa18e188a501c25c57bc7b80799
[7730:7751:0517/223228.640726:ERROR:browser_process_sub_thread.cc(209)] Waited 13 ms for network service
Opening in existing browser session.
/home/edoalvar/.local/lib/python2.7/site-packages/jupyter_client/kernelspec.py:253: UserWarning: Invalid kernelspec directory name (Kernel names can only contain ASCII letters and numbers and these separators: - . _ (hyphen, period, and underscore).): /home/edoalvar/.local/share/jupyter/kernels/julia-(4-threads)-1.1
  d = self.find_kernel_specs()
[W 22:32:35.121 NotebookApp] 404 GET /nbextensions/collapsible_headings.js?v=20190517223228 (127.0.0.1) 5.69ms referer=http://localhost:8888/notebooks/201905/getdatabaseworkingJulia110.ipynb
[W 22:32:35.130 NotebookApp] 404 GET /nbextensions/hide_input.js?v=20190517223228 (127.0.0.1) 1.26ms referer=http://localhost:8888/notebooks/201905/getdatabaseworkingJulia110.ipynb
[I 22:32:35.264 NotebookApp] Kernel started: 32d7ff13-ff29-455e-9092-c83dff94b120
[W 22:32:35.287 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190517223228 (127.0.0.1) 1.28ms referer=http://localhost:8888/notebooks/201905/getdatabaseworkingJulia110.ipynb
Starting kernel event loops.
[I 22:32:39.460 NotebookApp] Adapting to protocol v5.0 for kernel 32d7ff13-ff29-455e-9092-c83dff94b120
```

**Comment by travigd** [comment] 2019-05-18 04:51
The `display` is going to be problematic (it uses Jupyter's display method which is kind of orthogonal to the way WebIO/Interact work). Does it work if you just do this?
```julia
using Interact

@manipulate for npp=1:180
    npp
end
```

Also, are there any error messages in the browser console? Thank you for being patient and helping debug!

**Comment by EdoAlvarezR** [comment] 2019-05-18 18:33
It didn't change anything. The interact is still not updating:

![image](https://user-images.githubusercontent.com/14857108/57973603-b282ff80-7968-11e9-98e4-0f7d4206c9ad.png)

No errors show up in the browser console. This is the console from launching Jupyter up to running those cells.

```bash
edoalvar@edoalvar:~/Dropbox/FLOWResearch/LabNotebook$ jupyter notebook &
[I 12:26:26.785 NotebookApp] Serving notebooks from local directory: /home/edoalvar/Dropbox/FLOWResearch/LabNotebook
[I 12:26:26.785 NotebookApp] The Jupyter Notebook is running at:
[I 12:26:26.785 NotebookApp] http://localhost:8888/?token=0379bbfed8e450c9710ed759a1f28b94396f7618c1015e71
[I 12:26:26.785 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:26:26.787 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///run/user/1000/jupyter/nbserver-21959-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=0379bbfed8e450c9710ed759a1f28b94396f7618c1015e71
[21972:21993:0518/122627.071716:ERROR:browser_process_sub_thread.cc(209)] Waited 14 ms for network service
Opening in existing browser session.
/home/edoalvar/.local/lib/python2.7/site-packages/jupyter_client/kernelspec.py:253: UserWarning: Invalid kernelspec directory name (Kernel names can only contain ASCII letters and numbers and these separators: - . _ (hyphen, period, and underscore).): /home/edoalvar/.local/share/jupyter/kernels/julia-(4-threads)-1.1
  d = self.find_kernel_specs()
[W 12:26:28.305 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20190518122626 (127.0.0.1) 7.81ms referer=http://localhost:8888/tree
[W 12:27:31.155 NotebookApp] 404 GET /nbextensions/collapsible_headings.js?v=20190518122626 (127.0.0.1) 1.21ms referer=http://localhost:8888/notebooks/201905/getdatabaseworkingJulia110.ipynb
[W 12:27:31.163 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/config_menu/main.js?v=20190518122626 (127.0.0.1) 1.39ms referer=http://localhost:8888/notebooks/201905/getdatabaseworkingJulia110.ipynb
[W 12:27:31.169 NotebookApp] 404 GET /nbextensions/hide_input.js?v=20190518122626 (127.0.0.1) 2.38ms referer=http://localhost:8888/notebooks/201905/getdatabaseworkingJulia110.ipynb
[I 12:27:31.330 NotebookApp] Kernel started: f53f970f-abe4-45b6-813d-089889db63db
[W 12:27:31.339 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190518122626 (127.0.0.1) 1.53ms referer=http://localhost:8888/notebooks/201905/getdatabaseworkingJulia110.ipynb
Starting kernel event loops.
[I 12:27:35.318 NotebookApp] Adapting to protocol v5.0 for kernel f53f970f-abe4-45b6-813d-089889db63db
```

**Comment by travigd** [comment] 2019-05-27 01:09
@EdoAlvarezR I can't reproduce this on a brand new installation of Interact (using a Docker container). Can you message me on the JuliaLang slack so we can do some interactive debugging?

**Comment by ronin3alanRiva** [comment] 2019-06-16 13:04
I have the same issue as @EdoAlvarezR  when starting jupyter notebook from the terminal. If I start the notebook from a julia terminal with "using IJulia, Interact" and then "notebook(dir = Interact.notebookdir)
" the slider example updates. But if I use a folder different from Interact.notebookdir then it does not update anymore. Maybe this can help find the bug.

**Comment by drippdropp** [comment] 2019-12-31 18:44
I have the same issue as @ronin3alanRiva described.

UI elements display correctly in all case, but unless I launch the notebook from the `julia` REPL, the UI elements do not actually trigger any change when manipulated.

**Comment by travigd** [comment] 2020-01-02 19:48
Hi, this issue has become long and overloaded. I'm going to close it.

If you have problems, please open a new issue, include your version of Julia, package versions, and an attempt at a MWE. This would be very much appreciated.

**Closed by travigd** 2020-01-02 19:48 UTC
