### ISSUE TITLE
Documentation & garbage collection.

### ISSUE THREAD

**Issue by ma-laforge** [JuliaGizmos/Interact.jl#128] opened 2016-12-04 17:39 UTC
Hi,

I wanted to point out a potential garbage collection issue that might be nice to add in the documentation one day.  I lost quite a bit of time "fixing" this issue.

It appears that signals that go out of variable scope get garbage collected, and stop "signalling".  Though this makes sense for Julia, I was not expecting it coming from a C/C++ background.

Note that this behaviour is actually a **good** thing... because it means re-running code & re-defining `Signals` does not keep adding more-and-more `Signal`s in the messaging queue (or whatever is being used).

Here is an example of when I got tripped up:
```
updatersignal = map((src_signal_val)->push!(dest_signal, src_signal_val), src_signal)
```

I have used the above pattern in the past *without* assigning to `updatersignal` (because I don't intend on displaying this update mechanism-type "signal").  **Result:** The updates sort of happened for a second or two... but then just magically stopped!

It took me quite a bit of time to realize this happened because garbage collection threw away my updater signal.

**Comment by yuyichao** [comment] 2016-12-04 18:37
FWIW, it is a bad idea to rely on the finalizer to disconnect signals with side effects. It's actually a good idea in C++ but definitely not in julia.

**Comment by ma-laforge** [comment] 2016-12-05 23:21
RE: Not a good idea in Julia:

I never really thought of this.  Are you saying this because C++ destructors occur at known instances (@ end of variable scope or when explicitly destroyed) - whereas Julia variables have a very different lifespan (gc happens when it happens)?

Hmmm... If so, I will have to keep that in mind for the future.

I must say though:  It seems to me that having Signals destroyed once overwritten with new ones (due to the user re-executing an IJulia code block) does feel like the right thing to do... at least in this particular instance.

I think it would be a bad thing to keep accumulating more-and-more Signals in the messaging queue as the user re-executes code blocks

Would there be a better way to get this behaviour without relying on the finalizer mechanism?

**Comment by yuyichao** [comment] 2016-12-06 00:34
>  It seems to me that having Signals destroyed once overwritten with new ones

This is not well defined in julia (assignment is not an action on the object) so it's not a good idea. It is in C++ because assigning is a well defined operation on the object.

> Would there be a better way to get this behaviour without relying on the finalizer mechanism?

Always disconnect explicitly.

**Comment by piever** [comment] 2018-07-12 13:54
Seems like a duplicate of #173 . In the latest (unreleased) version of Interact, `map` (that now is called `on`) stores the behavior in the `Observable` and can be disconnected explicity:

```julia
o = Observable(1)
f = on(println, o) # Now o has a "listener" that triggers whenever o changes
off(f, o)
```

**Closed by piever** 2018-07-12 13:54 UTC
