### ISSUE TITLE
example from tutorial fails: no method matching show(...)

### ISSUE THREAD

**Issue by fzag** [JuliaGizmos/Interact.jl#236] opened 2018-07-08 08:38 UTC
Hello,

The simplest example from the tutorial (when using Blink) doesn't work

```julia
using Interact, Blink
ui = button()
w = Window()
body!(w, ui);
```

I get:
```
ERROR: MethodError: no method matching show(::IOContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("text/html")}, ::Interact.Button{Void})
```

i am using Julia 0.6.2, with:
* Blink                         0.6.2
* Interact                      0.7.2
* WebIO                         0.2.4

on mac OS 10.13.3

Does anyone has an idea? I am doing something wrong?
thank you very much :)

Franck

**Comment by piever** [comment] 2018-07-08 11:31
Duplicate of #230 

The documentation refers to the unreleased version of Interact, to try out the new version, you need to do `Pkg.checkout("Interact")` in the REPL.

**Closed by piever** 2018-07-08 11:31 UTC
