### ISSUE TITLE
Pkg.add fails in Centos

### ISSUE THREAD

**Issue by vdayanand** [JuliaGizmos/Interact.jl#233] opened 2018-06-13 14:09 UTC
I am using Julia0.6.3
```
julia> Pkg.add("Interact")
INFO: Cloning cache of DataStructures from https://github.com/JuliaCollections/DataStructures.jl.git
INFO: Cloning cache of Interact from https://github.com/JuliaGizmos/Interact.jl.git
INFO: Cloning cache of Reactive from https://github.com/JuliaGizmos/Reactive.jl.git
INFO: Installing DataStructures v0.8.3
INFO: Installing Interact v0.7.2
INFO: Installing Reactive v0.7.0
INFO: Building Interact
INFO: Enabling widgetsnbextension
Installing /home/osboxes/.local/lib/python2.7/site-packages/widgetsnbextension/static -> jupyter-js-widgets
Traceback (most recent call last):
  File "/home/osboxes/.local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/osboxes/.local/lib/python2.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/osboxes/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/osboxes/.local/lib/python2.7/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/home/osboxes/.local/lib/python2.7/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/home/osboxes/.local/lib/python2.7/site-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/home/osboxes/.local/lib/python2.7/site-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/home/osboxes/.local/lib/python2.7/site-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    destination=dest, logger=logger
  File "/home/osboxes/.local/lib/python2.7/site-packages/notebook/nbextensions.py", line 126, in install_nbextension
    ensure_dir_exists(nbext)
  File "/home/osboxes/.local/lib/python2.7/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/share/jupyter'
WARNING: Could not enable widgetsnbextension.
INFO: widgetsnbextension version found: 3.2.1
INFO: A compatible version of widgetsnbextension was found. All good.
INFO: Package database updated

julia> 
```

**Comment by piever** [comment] 2018-06-14 17:17
Looks like you are using a jupyter notebook installed in `/usr/local/share` rather than the private  within Julia version provided by IJulia.jl and Conda.jl (which would be inside `.julia/v0.6` folder). As a consequence, Julia would probably need super-user permissions to enable widgetsnbextension.

Possible fixes:

- follow instructions [here](https://github.com/JuliaLang/IJulia.jl) to instead use a private Julia version of jupyter notebook
- maybe there's a way on CentOS to run Julia with super-user permissions so that it can enable widgetsnbextension in `/usr/local/share/jupyter` (not sure whether that's recommended)

However, as Interact (on master) no longer relies on widgetsnbextension you could also do `Pkg.checkout("Interact")` and see whether Interact master works out of the box for your setup. If you have no prior code using Interact, this is probably a good idea anyway as the next release will be a bit breaking, so you avoid having to rewrite your code.

**Comment by piever** [comment] 2018-07-11 16:37
Closing as the issue is widgetsnbextension specific and this package no longer relies on that extension.

**Closed by piever** 2018-07-11 16:37 UTC
