### ISSUE TITLE
Slider label off-by-one with range starting at anything but one

### ISSUE THREAD

**Issue by milesfrain** [JuliaGizmos/Interact.jl#313] opened 2019-06-04 03:30 UTC
`s = slider(0:3)`
Shows the following labels for each of the actual positions returned by `s[]`.
```
s[]     Label

0      *blank*
1         0
2         1
3         2
```

There's also a bug with `s = slider(2:3)`
```
s[]     Label

2         3
3      *blank*
```

Ranges `1:3` and `1:2` work fine.

This may be related to #309. I haven't tried InteractBase master. Tested in Juno.

**Comment by piever** [comment] 2019-06-04 15:48
I've just tagged a release of InteractBase, so this should be fixed. Feel free to reopen if the problem is still there after updating.

**Closed by piever** 2019-06-04 15:48 UTC
