### ISSUE TITLE
Widgets don't appear

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaGizmos/Interact.jl#199] opened 2017-12-15 21:13 UTC
The following code in Jupyter Notebook does not display widgets. It just shows a regular Gadfly plot with no interactivity.
```
using Interact
using Gadfly

@manipulate for θ=0:π/16:π
    x = collect(linspace(0, 1))
    plot(x=x, y=sin.(θ * x))
end
```

Julia v0.6, Ubuntu 14.04, `Pkg.add("Interact"); Pkg.build("Interact")` gives:
```
INFO: Building Interact
INFO: Enabling widgetsnbextension
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
INFO: ipywidgets version found: 6.0.0
INFO: A compatible version of ipywidgets was found. All good.
```
so I don't know what is wrong.

**Comment by korsbo** [comment] 2017-12-18 11:58
I'm not an expert, but this looks to me like a problem with ipywidgets. Have you had a look at #182?

**Comment by juliohm** [comment] 2017-12-25 19:57
I can confirm the issue. I had used the solution described in #182 before, but it is not working anymore. I am on `python-ipywidgets 6.0.0-1` and the master branch of Interact.jl.

**Comment by juliohm** [comment] 2018-01-05 20:24
A workaround for anyone that needs the Interact.jl functionality for teaching classes and presentations is to use the InteractNext.jl package instead. I've just installed it and it is working well, the only downside is that it is a little slower than Interact.jl with Plots.jl in IJulia.

**Comment by SimonEnsemble** [comment] 2018-01-05 20:27
@juliohm thanks! Were you able to download the complete interactive viz to host on a website, e.g. Github pages?

**Comment by juliohm** [comment] 2018-01-05 20:52
Hi @SimonDanisch I didn't try to host the visualizations on a website, I am planning a more hands-on experience with students in the class, and may update the notebooks to GitHub at some point.

**Comment by stevengj** [comment] 2018-01-11 02:53
@juliohm, see my comment here: https://github.com/JuliaGizmos/Interact.jl/issues/182#issuecomment-356808626

ipywidgets 7.0.5 seems to work fine for me — the problem is if you have multiple `jupyter` versions installed and Interact is configured with a different one than the one you are actually running.

**Comment by juliohm** [comment] 2018-01-11 03:11
Thank you @stevengj , `IJulia.jupyter` returns "jupyter" on my laptop, is there any other way to print out the version conflict?

**Comment by stevengj** [comment] 2018-01-11 13:14
@juliohm, Interact's build script uses
```jl
python = strip(readline(readstring(`which $(IJulia.jupyter)`)|>strip), ['\n',' ', '#','!'])
```
to find the path of the Python that it thinks Jupyter is using, at least on Unix systems.  On Windows systems, it just runs `python`, which isn't really right.

What operating system are you using?  How are you running `jupyter`?  Are you just typing `jupyter` on the command line?

**Comment by juliohm** [comment] 2018-01-12 04:21
@stevengj I am on Linux. Calling Jupyter directly from the terminal (jupyter notebook) or from IJulia (using IJulia; notebook()) has the same effect. None of them work here.

**Comment by korsbo** [comment] 2018-02-21 11:23
@mbaz you could try to install ipywidgets 7+. This works for me, but ipywidgets 6 does not. 

```bash
pip install ipywidgets==7.1.1
```
Then restart jupyter. 

you may also need to create file under `Interact/deps` called `ipywidgets_version` containing your ipywidgets version (as the name may suggest.)

```bash 
echo "7.1.1"  > ~/.julia/v0.6/Interact/deps/ipywidgets_version
```

I make no guarantees, but this worked for me.

**Comment by mbaz** [comment] 2018-02-21 15:16
@korsbo Thanks so much. I didn't want to fight package dependencies, and in Arch the ipywidgets package is outdated. I just went ahead and removed jupyter completely from my system and re-build IJulia, which pulled its own packages. Now everything works.

BTW, I didn't have to touch `deps/ipywidgets_version`; re-building `Interact` did the right thing.

**Comment by piever** [comment] 2018-07-11 17:12
Closing this as the latest (unreleased) version of Interact no longer relies on ipywidgets and the example in the first post seems to work just fine.

**Closed by piever** 2018-07-11 17:12 UTC
